import { chromium } from "playwright";
import { readFileSync } from "node:fs";
const he = JSON.parse(readFileSync("/home/user/FoodMamkor/frontend/messages/he.json","utf8"));
const CTA = he.group_buys.detail.cancel_cta;
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
p.on("console", m => console.log("[console]", m.text().slice(0,200)));
await p.addInitScript(() => { try { localStorage.setItem("token","qa-token"); } catch {} });
const seen = [];
await p.route("**/api/**", (r) => { seen.push("CATCHALL "+r.request().url()); return r.fulfill({status:200,contentType:"application/json",body:"null"}); });
await p.route("**/api/auth/me", (r) => { seen.push("ME "+r.request().url()); return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({id:1,name:"דנה",email:"d@e.com",role:"user",phone:"0500000000"})}); });
await p.route("**/api/group-buys/gb-1", (r) => { seen.push("GB "+r.request().url()); return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({id:"gb-1",title:"קבוצה",status:"open",deadline:"2099-01-01T00:00:00Z",min_participants:2,max_participants:10,commits_count:1,price_per_unit_regular:100,price_per_unit_group:80,user_committed:true,user_commit:{quantity:1}})}); });
await p.goto("http://127.0.0.1:3000/he/group-buys/gb-1", { waitUntil: "networkidle", timeout: 15000 }).catch(e=>console.log("goto:",e.message.slice(0,80)));
await p.waitForTimeout(1500);
console.log("URL:", p.url());
console.log("ROUTES SEEN:", seen);
console.log("CTA string:", JSON.stringify(CTA));
const buttons = await p.$$eval("button", els => els.map(e => e.textContent.trim().slice(0,40)));
console.log("BUTTONS:", buttons);
console.log("BODY SNIPPET:", (await p.textContent("body")).replace(/\s+/g," ").slice(0,400));
await b.close();
