// Generates the synth-entry barrel + componentSrcMap for the Mehamakor frontend.
// Run from repo root: node .design-sync/gen-barrel.mjs
// Emits:
//   frontend/.ds-barrel.mjs   — re-exports every component as its PascalCase name
//   .design-sync/.cache/srcmap.json — {Name: "components/<rel>.jsx"} for cfg.componentSrcMap
import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const FE = 'frontend';
const COMP = join(FE, 'components');

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (/\.jsx$/.test(e.name)) out.push(p);
  }
  return out;
}

// Excluded: leaflet-CSS importers. Bundling them makes esbuild emit CSS, which
// would force the brand-font @imports mid-file (invalid). Map widgets aren't DS
// components anyway. Reported to the user.
const EXCLUDE = new Set(['HomepageMiniMap', 'MapComponent', 'MiniMap']);

// Files whose exports don't match the filename — map name → source-relative path.
const EXTRAS = {
  SkeletonCard: 'components/Skeleton.jsx',
  SkeletonLine: 'components/Skeleton.jsx',
  SkeletonProducerGrid: 'components/Skeleton.jsx',
};

const files = walk(COMP).sort();
const barrel = [];
const srcMap = {};
const skipped = [];
const seen = new Map();

for (const f of files) {
  const base = f.replace(/\.jsx$/, '').split(/[\\/]/).pop(); // filename sans ext
  const name = base; // files are already PascalCase
  if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) { skipped.push([f, 'non-PascalCase']); continue; }
  if (EXCLUDE.has(name)) { skipped.push([f, 'excluded (leaflet CSS cluster)']); continue; }
  if (seen.has(name)) { skipped.push([f, `name collision with ${seen.get(name)}`]); continue; }
  const src = readFileSync(f, 'utf8');
  // path relative to barrel (frontend/), forward slashes, keep extension
  const rel = './' + relative(FE, f).replace(/\\/g, '/');
  let line;
  if (/export\s+default/.test(src)) {
    line = `export { default as ${name} } from ${JSON.stringify(rel)};`;
  } else if (new RegExp(`export\\s+(?:async\\s+)?(?:function|const|let|var|class)\\s+${name}\\b`).test(src)
          || new RegExp(`export\\s*\\{[^}]*\\b${name}\\b`).test(src)) {
    line = `export { ${name} } from ${JSON.stringify(rel)};`;
  } else {
    skipped.push([f, 'no default and no matching named export']);
    continue;
  }
  barrel.push(line);
  seen.set(name, f);
  // componentSrcMap path is PKG_DIR(=frontend)-relative
  srcMap[name] = relative(FE, f).replace(/\\/g, '/');
}

for (const [name, rel] of Object.entries(EXTRAS)) {
  if (seen.has(name)) continue;
  barrel.push(`export { ${name} } from ${JSON.stringify('./' + rel)};`);
  srcMap[name] = rel;
  seen.set(name, rel);
}
barrel.sort();

const header = '// AUTO-GENERATED by .design-sync/gen-barrel.mjs — synth-entry barrel for design-sync.\n'
  + '// Re-exports every frontend component onto window.MehamakorDS.* via the converter.\n';
writeFileSync(join(FE, '.ds-barrel.mjs'), header + barrel.join('\n') + '\n');

mkdirSync('.design-sync/.cache', { recursive: true });
writeFileSync('.design-sync/.cache/srcmap.json', JSON.stringify(srcMap, null, 2) + '\n');

console.error(`barrel: ${barrel.length} components exported`);
console.error(`skipped: ${skipped.length}`);
for (const [f, why] of skipped) console.error(`  - ${f}: ${why}`);
