"""baseline

Revision ID: ef8fb1858f5b
Revises: 
Create Date: 2026-04-24 08:15:32.029430+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef8fb1858f5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_he', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_he')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('outreach_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('prefill_token', sa.String(length=64), nullable=True),
    sa.Column('prefill_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_leads_prefill_token'), 'outreach_leads', ['prefill_token'], unique=True)
    op.create_table('producers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('whatsapp_group', sa.String(length=300), nullable=True),
    sa.Column('primary_contact_method', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('story_card_url', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('top_product_name', sa.String(length=200), nullable=True),
    sa.Column('starting_price_label', sa.String(length=50), nullable=True),
    sa.Column('price_range', sa.String(length=100), nullable=True),
    sa.Column('grass_fed', sa.Boolean(), nullable=True),
    sa.Column('organic_certified', sa.Boolean(), nullable=True),
    sa.Column('gluten_free', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('lactose_free', sa.Boolean(), nullable=True),
    sa.Column('has_delivery', sa.Boolean(), nullable=True),
    sa.Column('pickup_points', sa.Boolean(), nullable=True),
    sa.Column('kosher', sa.String(length=50), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('is_available_today', sa.Boolean(), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=True),
    sa.Column('vacation_until', sa.Date(), nullable=True),
    sa.Column('opening_hours', sa.String(), nullable=True),
    sa.Column('has_physical_location', sa.Boolean(), nullable=False),
    sa.Column('offers_delivery', sa.Boolean(), nullable=False),
    sa.Column('delivery_nationwide', sa.Boolean(), nullable=False),
    sa.Column('delivery_cities', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('ambassador', sa.Boolean(), nullable=True),
    sa.Column('kashrut_badges', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('kashrut_verified_at', sa.DateTime(), nullable=True),
    sa.Column('kashrut_expires_at', sa.DateTime(), nullable=True),
    sa.Column('custom_questions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_producers_name', 'producers', [sa.text("to_tsvector('simple', name)")], unique=False, postgresql_using='gin')
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('static_pages',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('category_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requested_name', sa.String(length=100), nullable=False),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('producer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_requests_producer_id'), 'category_requests', ['producer_id'], unique=False)
    op.create_index(op.f('ix_category_requests_status'), 'category_requests', ['status'], unique=False)
    op.create_table('delivery_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('min_order', sa.Integer(), nullable=True),
    sa.Column('delivery_day', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_buys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('price_per_unit_regular', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_unit_group', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_participants', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_buys_producer_id'), 'group_buys', ['producer_id'], unique=False)
    op.create_table('phone_otp_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otp_tokens_producer_id'), 'phone_otp_tokens', ['producer_id'], unique=False)
    op.create_table('producer_categories',
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producer_id', 'category_id')
    )
    op.create_table('producer_page_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('viewer_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_page_views_created_at'), 'producer_page_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_producer_page_views_producer_id'), 'producer_page_views', ['producer_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('producer_id', sa.UUID(), nullable=True),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('apple_id', sa.String(length=200), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('is_producer', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verify_token', sa.String(length=64), nullable=True),
    sa.Column('email_verify_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email_verify_token'), 'users', ['email_verify_token'], unique=False)
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('host_user_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_schedule', sa.Text(), nullable=True),
    sa.Column('location_type', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('moderation_status', sa.String(length=20), nullable=True),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('moderation_suggestion', sa.Text(), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('notify_new_product', sa.Boolean(), nullable=True),
    sa.Column('notify_new_event', sa.Boolean(), nullable=True),
    sa.Column('notify_delivery_area', sa.Boolean(), nullable=True),
    sa.Column('push_subscription', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'producer_id', name='uq_favorite_alert_per_producer')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'producer_id')
    )
    op.create_table('group_buy_commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_buy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_buy_id'], ['group_buys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_buy_id', 'user_id', name='uq_group_buy_user')
    )
    op.create_index(op.f('ix_group_buy_commits_group_buy_id'), 'group_buy_commits', ['group_buy_id'], unique=False)
    op.create_index(op.f('ix_group_buy_commits_user_id'), 'group_buy_commits', ['user_id'], unique=False)
    op.create_table('home_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('prep_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('storage_type', sa.String(length=30), nullable=True),
    sa.Column('allergens', sa.Text(), nullable=True),
    sa.Column('kosher', sa.String(length=30), nullable=True),
    sa.Column('is_organic', sa.Boolean(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('delivery_method', sa.String(length=30), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('moderation_status', sa.String(length=20), nullable=True),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('moderation_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kashrut_badge_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('badge_code', sa.String(length=50), nullable=False),
    sa.Column('cert_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kashrut_badge_requests_producer_id'), 'kashrut_badge_requests', ['producer_id'], unique=False)
    op.create_table('producer_contact_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_clicks_producer_at', 'producer_contact_clicks', ['producer_id', 'clicked_at'], unique=False)
    op.create_index(op.f('ix_producer_contact_clicks_clicked_at'), 'producer_contact_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_producer_contact_clicks_producer_id'), 'producer_contact_clicks', ['producer_id'], unique=False)
    op.create_index(op.f('ix_producer_contact_clicks_user_id'), 'producer_contact_clicks', ['user_id'], unique=False)
    op.create_table('producer_followers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('notify_new_products', sa.Boolean(), nullable=True),
    sa.Column('notify_back_in_stock', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'producer_id', name='uq_one_follow_per_user_producer')
    )
    op.create_table('producer_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producer_id', 'user_id', name='uq_one_review_per_producer_per_user')
    )
    op.create_table('producer_whatsapp_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_whatsapp_clicks_clicked_at'), 'producer_whatsapp_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_producer_whatsapp_clicks_producer_id'), 'producer_whatsapp_clicks', ['producer_id'], unique=False)
    op.create_index(op.f('ix_producer_whatsapp_clicks_user_id'), 'producer_whatsapp_clicks', ['user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referee_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_clicks_referee_id'), 'referral_clicks', ['referee_id'], unique=False)
    op.create_index(op.f('ix_referral_clicks_referrer_id'), 'referral_clicks', ['referrer_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_product_whatsapp_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('home_product_id', sa.UUID(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('rating_sent', sa.Boolean(), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=True),
    sa.Column('rating_token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['home_product_id'], ['home_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating_token')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=200), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_product_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('click_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('home_product_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['click_id'], ['home_product_whatsapp_clicks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_product_id'], ['home_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('click_id', name='uq_one_rating_per_click')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_product_ratings')
    op.drop_table('recipe_ingredients')
    op.drop_table('home_product_whatsapp_clicks')
    op.drop_table('reports')
    op.drop_index(op.f('ix_referral_clicks_referrer_id'), table_name='referral_clicks')
    op.drop_index(op.f('ix_referral_clicks_referee_id'), table_name='referral_clicks')
    op.drop_table('referral_clicks')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_producer_whatsapp_clicks_user_id'), table_name='producer_whatsapp_clicks')
    op.drop_index(op.f('ix_producer_whatsapp_clicks_producer_id'), table_name='producer_whatsapp_clicks')
    op.drop_index(op.f('ix_producer_whatsapp_clicks_clicked_at'), table_name='producer_whatsapp_clicks')
    op.drop_table('producer_whatsapp_clicks')
    op.drop_table('producer_reviews')
    op.drop_table('producer_followers')
    op.drop_index(op.f('ix_producer_contact_clicks_user_id'), table_name='producer_contact_clicks')
    op.drop_index(op.f('ix_producer_contact_clicks_producer_id'), table_name='producer_contact_clicks')
    op.drop_index(op.f('ix_producer_contact_clicks_clicked_at'), table_name='producer_contact_clicks')
    op.drop_index('ix_contact_clicks_producer_at', table_name='producer_contact_clicks')
    op.drop_table('producer_contact_clicks')
    op.drop_index(op.f('ix_kashrut_badge_requests_producer_id'), table_name='kashrut_badge_requests')
    op.drop_table('kashrut_badge_requests')
    op.drop_table('home_products')
    op.drop_index(op.f('ix_group_buy_commits_user_id'), table_name='group_buy_commits')
    op.drop_index(op.f('ix_group_buy_commits_group_buy_id'), table_name='group_buy_commits')
    op.drop_table('group_buy_commits')
    op.drop_table('favorites')
    op.drop_table('favorite_alerts')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.drop_index(op.f('ix_users_email_verify_token'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_index(op.f('ix_producer_page_views_producer_id'), table_name='producer_page_views')
    op.drop_index(op.f('ix_producer_page_views_created_at'), table_name='producer_page_views')
    op.drop_table('producer_page_views')
    op.drop_table('producer_categories')
    op.drop_index(op.f('ix_phone_otp_tokens_producer_id'), table_name='phone_otp_tokens')
    op.drop_table('phone_otp_tokens')
    op.drop_index(op.f('ix_group_buys_producer_id'), table_name='group_buys')
    op.drop_table('group_buys')
    op.drop_table('events')
    op.drop_table('delivery_areas')
    op.drop_index(op.f('ix_category_requests_status'), table_name='category_requests')
    op.drop_index(op.f('ix_category_requests_producer_id'), table_name='category_requests')
    op.drop_table('category_requests')
    op.drop_table('static_pages')
    op.drop_table('search_queries')
    op.drop_index('idx_producers_name', table_name='producers', postgresql_using='gin')
    op.drop_table('producers')
    op.drop_index(op.f('ix_outreach_leads_prefill_token'), table_name='outreach_leads')
    op.drop_table('outreach_leads')
    op.drop_table('newsletter_subscribers')
    op.drop_table('contact_messages')
    op.drop_table('cities')
    op.drop_table('categories')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
